-- 004 — состояние двухшаговых переходов и пакеты модерации (SRS §2.12, §2.15).

CREATE TYPE bot_prompt_kind AS ENUM ('REASON_TEXT', 'DUPLICATE_NUMBER');

-- Минимальное состояние для переходов, требующих текста: «другое» и номер оригинала.
-- Ключ — сообщение бота с ForceReply, потому что ответ приходит именно на него.
CREATE TABLE bot_prompt (
    chat_id     BIGINT          NOT NULL,
    message_id  INTEGER         NOT NULL,
    report_id   INTEGER         NOT NULL,
    kind        bot_prompt_kind NOT NULL,
    -- Куда ведёт переход, ради которого спрошен текст. У DUPLICATE_NUMBER цель одна
    -- и известна, у REASON_TEXT их две — «отклонить» и «не по силам», — и различить их
    -- в момент ответа больше нечем: ответ приходит обычным сообщением, без callback_data.
    target_status report_status,
    -- Отвечать может только тот, кто начал переход. Проверка серверная (SRS §6.5).
    moderator_id INTEGER        NOT NULL,
    expires_at  TIMESTAMPTZ(3)  NOT NULL,

    CONSTRAINT bot_prompt_pkey PRIMARY KEY (chat_id, message_id),
    CONSTRAINT bot_prompt_report_id_fkey FOREIGN KEY (report_id) REFERENCES report (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT bot_prompt_moderator_id_fkey FOREIGN KEY (moderator_id) REFERENCES moderator (id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TYPE moderation_batch_kind AS ENUM ('DIGEST', 'DUPLICATE_CLUSTER');

-- Существует ровно потому, что callback_data ограничен 64 байтами: список из тридцати
-- номеров туда не помещается, а `1:B:417:AC` — помещается (SRS §2.15).
CREATE TABLE moderation_batch (
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind                    moderation_batch_kind NOT NULL,
    -- Состав, зафиксированный в момент отправки сообщения, а не пересчитываемый при
    -- нажатии: иначе модератор нажимал бы «принять все» на один список, а применялось
    -- бы к другому. Для DUPLICATE_CLUSTER первый элемент — корень кластера.
    report_ids              INTEGER[]      NOT NULL,
    chat_id                 BIGINT         NOT NULL,
    message_id              INTEGER,
    -- Защита от повторного применения: второе нажатие получает «пакет уже обработан».
    applied_at              TIMESTAMPTZ(3),
    applied_by_moderator_id INTEGER,
    created_at              TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

    CONSTRAINT moderation_batch_applied_by_fkey FOREIGN KEY (applied_by_moderator_id) REFERENCES moderator (id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Строка истории знает свой пакет. Связь по внешнему ключу, а не по совпадению времени:
-- отмена пакета правит опубликованные статусы, и держать её на равенстве created_at
-- значило бы, что любая будущая вставка истории отдельной транзакцией или перенос данных
-- ломают отмену молча и задним числом.
ALTER TABLE report_status_history
    ADD COLUMN batch_id INTEGER,
    ADD CONSTRAINT report_status_history_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES moderation_batch (id) ON DELETE SET NULL ON UPDATE CASCADE;

-- Частичный: заполнен только у пакетных решений, а их доля в истории мала.
CREATE INDEX history_batch_idx ON report_status_history (batch_id) WHERE batch_id IS NOT NULL;
