-- 004 — очередь доставки в Telegram и идемпотентность апдейтов (SRS §2.10, §2.11).

CREATE TYPE telegram_outbox_kind AS ENUM ('CARD_CREATE', 'CARD_EDIT', 'REPLY', 'ALERT');

-- Одна таблица закрывает три задачи: повтор при недоступном Telegram, схлопывание
-- нескольких правок одной карточки и отложенное на 15 минут снятие кнопки отмены
-- (SRS §6.10). Отдельного планировщика в системе нет — здесь уже есть колонка «когда».
CREATE TABLE telegram_outbox (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- NULL у digest: пакет ссылается на десять заявок сразу, и ни одна из них не «его».
    report_id       INTEGER,
    kind            telegram_outbox_kind NOT NULL,
    -- Готовый набор аргументов вызова Bot API для REPLY и ALERT. У CARD_CREATE
    -- и CARD_EDIT здесь пусто: карточка рендерится в момент отправки, иначе схлопнутая
    -- правка ушла бы с устаревшим текстом, а отложенная на 15 минут — с кнопкой отмены,
    -- которой уже нет (SRS §6.6, §6.10).
    payload         JSONB          NOT NULL,
    next_attempt_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
    attempts        SMALLINT       NOT NULL DEFAULT 0,
    last_error      VARCHAR(500),
    sent_at         TIMESTAMPTZ(3),

    CONSTRAINT telegram_outbox_report_id_fkey FOREIGN KEY (report_id) REFERENCES report (id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Частичный: воркер спрашивает только неотправленное, и индекс равен глубине очереди,
-- а не числу отправленных за кампанию сообщений.
CREATE INDEX outbox_due_idx ON telegram_outbox (next_attempt_at) WHERE sent_at IS NULL;

-- Первый рубеж идемпотентности: строка вставляется в той же транзакции, что и эффект,
-- поэтому повторная доставка апдейта отваливается на конфликте PK (SRS §6.11).
CREATE TABLE processed_update (
    update_id  BIGINT PRIMARY KEY,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now()
);
