-- 002 — заявка (SRS §2.1, §2.2).

CREATE TYPE report_status AS ENUM (
    'NEW', 'ACCEPTED', 'IN_PROGRESS', 'DONE', 'REJECTED', 'DUPLICATE', 'OUT_OF_SCOPE'
);

-- Номер выдаёт последовательность, а не COUNT(*) + 1: nextval атомарен и не берёт
-- блокировок, поэтому 1000 вставок в час не дают ни одного дубликата (SRS §2.1).
-- Стартовое значение — из SRS §2.1: счёт с RR-3471 выглядит как продолжение уже идущей
-- работы, а не как первый день кампании.
CREATE SEQUENCE report_public_number_seq START WITH 3471;

CREATE TABLE report (
    id                        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_number             INTEGER      NOT NULL DEFAULT nextval('report_public_number_seq'),
    status                    report_status NOT NULL DEFAULT 'NEW',
    category_id               INTEGER      NOT NULL,
    district_code             VARCHAR(32)  NOT NULL,
    latitude                  DECIMAL(9,6) NOT NULL,
    longitude                 DECIMAL(9,6) NOT NULL,
    landmark                  VARCHAR(200),
    contact_phone             VARCHAR(20),
    contact_telegram          VARCHAR(64),
    contacts_deleted_at       TIMESTAMPTZ(3),
    tracking_token            VARCHAR(24)  NOT NULL,
    idempotency_key           UUID,
    duplicate_of_id           INTEGER,
    duplicate_candidate_of_id INTEGER,
    status_reason             VARCHAR(48),
    status_reason_text        VARCHAR(500),
    publication_url           VARCHAR(512),
    created_ip                INET,
    telegram_album_message_id INTEGER,
    telegram_card_message_id  INTEGER,
    created_at                TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
    updated_at                TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
    done_at                   TIMESTAMPTZ(3),

    -- Грубый sanity-check на случай перепутанных местами широты и долготы; точный
    -- контроль — геозабор по полигонам (SRS §2.2, §3.3).
    CONSTRAINT report_latitude_check  CHECK (latitude  BETWEEN 41.0 AND 41.6),
    CONSTRAINT report_longitude_check CHECK (longitude BETWEEN 69.0 AND 69.7),

    -- Инварианты статусов. Они стоят в БД, а не только в коде: заявку правит и psql
    -- при разборе инцидента, а инвариант не должен зависеть от того, кто пишет.
    CONSTRAINT report_duplicate_target_check  CHECK (status <> 'DUPLICATE' OR duplicate_of_id IS NOT NULL),
    CONSTRAINT report_status_reason_check     CHECK (status NOT IN ('REJECTED', 'OUT_OF_SCOPE') OR status_reason IS NOT NULL),
    CONSTRAINT report_reason_text_check       CHECK (status_reason <> 'other' OR status_reason_text IS NOT NULL),
    CONSTRAINT report_done_at_check           CHECK ((status = 'DONE') = (done_at IS NOT NULL)),
    CONSTRAINT report_contacts_deleted_check  CHECK (contacts_deleted_at IS NULL
                                                     OR (contact_phone IS NULL AND contact_telegram IS NULL)),
    CONSTRAINT report_duplicate_self_check    CHECK (duplicate_of_id <> id),
    CONSTRAINT report_dup_candidate_self_check CHECK (duplicate_candidate_of_id <> id),

    CONSTRAINT report_category_id_fkey  FOREIGN KEY (category_id)   REFERENCES category (id)   ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT report_district_code_fkey FOREIGN KEY (district_code)  REFERENCES district (code) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT report_duplicate_of_id_fkey FOREIGN KEY (duplicate_of_id) REFERENCES report (id)  ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT report_duplicate_candidate_of_id_fkey FOREIGN KEY (duplicate_candidate_of_id) REFERENCES report (id) ON DELETE SET NULL ON UPDATE CASCADE
);

-- Последовательность принадлежит колонке: без OWNED BY Prisma видит её как посторонний
-- объект и предлагает удалить, а имя report_public_number_seq — то самое, которое
-- получилось бы у SERIAL, поэтому расхождения между схемой и миграцией здесь нет.
ALTER SEQUENCE report_public_number_seq OWNED BY report.public_number;

CREATE UNIQUE INDEX report_number_idx ON report (public_number);
CREATE UNIQUE INDEX report_token_idx  ON report (tracking_token);
CREATE UNIQUE INDEX report_idem_idx   ON report (idempotency_key) WHERE idempotency_key IS NOT NULL;

CREATE INDEX report_list_idx     ON report (created_at DESC, id DESC);
CREATE INDEX report_bbox_idx     ON report (latitude, longitude);
CREATE INDEX report_status_idx   ON report (status);
CREATE INDEX report_district_idx ON report (district_code, status);

-- Частичные: при десятках тысяч закрытых заявок остаются размером с активную очередь,
-- а не с таблицей (SRS §2.2). Prisma частичный индекс не описывает, поэтому они живут
-- только здесь — см. комментарий в schema.prisma.
CREATE INDEX report_done_idx    ON report (done_at DESC) WHERE done_at IS NOT NULL;
CREATE INDEX report_dupcand_idx ON report (duplicate_candidate_of_id) WHERE duplicate_candidate_of_id IS NOT NULL;
CREATE INDEX report_queue_idx   ON report (created_at) WHERE status = 'NEW';
