-- 004 — allowlist модераторов (SRS §2.8, ADR-0005).

CREATE TABLE moderator (
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_user_id      BIGINT       NOT NULL,
    -- Для журнала и строки «кто поставил» в карточке. Публично не показывается (PRD §6.2).
    -- Nullable: первичный засев знает только идентификаторы из TELEGRAM_MODERATOR_IDS.
    display_name          VARCHAR(120),
    -- Снятие полномочий — false, а не DELETE: внешний ключ из истории обязан пережить
    -- уход модератора, иначе след прошлых решений пришлось бы обнулять.
    is_active             BOOLEAN        NOT NULL DEFAULT true,
    added_at              TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
    -- NULL только у засеянных при первом развёртывании.
    added_by_moderator_id INTEGER,
    deactivated_at        TIMESTAMPTZ(3),

    CONSTRAINT moderator_added_by_fkey FOREIGN KEY (added_by_moderator_id) REFERENCES moderator (id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE UNIQUE INDEX moderator_telegram_user_id_key ON moderator (telegram_user_id);

-- Частичный: сверка нажавшего идёт только по активным, и индекс равен размеру бригады,
-- а не истории её состава (SRS §2.8).
CREATE INDEX moderator_active_idx ON moderator (telegram_user_id) WHERE is_active;

-- Связь, обещанная в 002: до появления таблицы историю писал только SYSTEM, поэтому
-- колонка стояла без внешнего ключа. RESTRICT, а не SET NULL: решение модератора
-- не должно терять автора при попытке удалить строку allowlist.
ALTER TABLE report_status_history
    ADD CONSTRAINT report_status_history_moderator_id_fkey
    FOREIGN KEY (moderator_id) REFERENCES moderator (id) ON DELETE RESTRICT ON UPDATE CASCADE;
