-- 002 — фотографии как очередь, сигналы антиабуза, счётчик открытий формы
-- (SRS §2.4, §2.9, §2.13).

CREATE TYPE photo_kind  AS ENUM ('BEFORE', 'AFTER');
CREATE TYPE photo_state AS ENUM ('PENDING', 'READY', 'FAILED');
CREATE TYPE abuse_rule  AS ENUM ('HONEYPOT', 'FAST_FILL', 'IP_RATE');

CREATE TABLE report_photo (
    id                           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id                    INTEGER     NOT NULL,
    kind                         photo_kind  NOT NULL,
    sort_order                   SMALLINT    NOT NULL,
    state                        photo_state NOT NULL DEFAULT 'PENDING',
    raw_key                      VARCHAR(160),
    object_key                   VARCHAR(160),
    preview_key                  VARCHAR(160),
    sha256                       CHAR(64),
    width                        SMALLINT,
    height                       SMALLINT,
    bytes                        INTEGER,
    attempts                     SMALLINT    NOT NULL DEFAULT 0,
    next_attempt_at              TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
    last_error                   VARCHAR(500),
    uploaded_by_telegram_user_id BIGINT,
    created_at                   TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

    CONSTRAINT report_photo_sort_order_check CHECK (sort_order BETWEEN 0 AND 2),
    -- READY без ключей и хеша — это строка, по которой нечего показать. Инвариант
    -- держит БД: воркер обновляет строку не одним оператором, и половинчатое
    -- состояние не должно быть представимо (SRS §2.4).
    CONSTRAINT report_photo_ready_check CHECK (state <> 'READY'
                                               OR (object_key IS NOT NULL
                                                   AND preview_key IS NOT NULL
                                                   AND sha256 IS NOT NULL)),

    CONSTRAINT report_photo_report_id_fkey FOREIGN KEY (report_id) REFERENCES report (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE UNIQUE INDEX photo_slot_idx  ON report_photo (report_id, kind, sort_order);
CREATE UNIQUE INDEX photo_dedup_idx ON report_photo (report_id, kind, sha256);

-- Очередь обработки целиком: строки, дошедшие до READY, из индекса выпадают, поэтому
-- его размер равен глубине очереди, а не числу фотографий (SRS §2.4, ADR-0007).
CREATE INDEX photo_queue_idx ON report_photo (next_attempt_at) WHERE state = 'PENDING';

CREATE TABLE abuse_signal (
    id         INTEGER    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id  INTEGER    NOT NULL,
    rule       abuse_rule NOT NULL,
    detail     JSONB,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

    CONSTRAINT abuse_signal_report_id_fkey FOREIGN KEY (report_id) REFERENCES report (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX abuse_signal_report_idx ON abuse_signal (report_id);

CREATE TABLE form_open_counter (
    day   DATE    PRIMARY KEY,
    count INTEGER NOT NULL
);
