-- 002 — история переходов (SRS §2.7).

CREATE TYPE actor_type AS ENUM ('SYSTEM', 'MODERATOR', 'VOLUNTEER');

CREATE TABLE report_status_history (
    id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id              INTEGER       NOT NULL,
    from_status            report_status,
    to_status              report_status NOT NULL,
    actor_type             actor_type    NOT NULL,
    actor_telegram_user_id BIGINT,
    -- Внешнего ключа на moderator пока нет: таблица приходит вместе с ботом в 004,
    -- и связь добавляется там же. В этом срезе историю пишет только SYSTEM.
    moderator_id           INTEGER,
    reason                 VARCHAR(48),
    reason_text            VARCHAR(500),
    duplicate_of_id        INTEGER,
    undone_at              TIMESTAMPTZ(3),
    undoes_history_id      INTEGER,
    created_at             TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

    CONSTRAINT report_status_history_report_id_fkey FOREIGN KEY (report_id) REFERENCES report (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT report_status_history_undoes_history_id_fkey FOREIGN KEY (undoes_history_id) REFERENCES report_status_history (id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE INDEX history_report_idx ON report_status_history (report_id, created_at);

-- Двойная отмена одного перехода отклоняется индексом, а не проверкой в коде:
-- проверка живёт в одном месте, а нажать «Отменить» можно из двух сессий сразу.
CREATE UNIQUE INDEX history_undo_once_idx ON report_status_history (undoes_history_id)
    WHERE undoes_history_id IS NOT NULL;
